# Generated by Django 5.0.1 on 2024-03-12 04:03

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedzipfile',
            name='progress',
            field=models.CharField(choices=[('starting_text_processing', 'Starting Text Processing'), ('text_processing_complete', 'Text Processing Complete'), ('starting_embedding', 'Starting Embedding'), ('embedding_complete', 'Embedding Complete'), ('error', 'error'), ('complete', 'complete')], default='starting_text_processing', max_length=50),
        ),
        migrations.AlterField(
            model_name='uploadedzipfile',
            name='uploaded_zip_file',
            field=models.FileField(upload_to='static/uploads/', validators=[app.models.validate_zip_file_size]),
        ),
        migrations.AlterField(
            model_name='user',
            name='bot_icon',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/'),
        ),
    ]
