# Generated by Django 5.0.1 on 2024-03-12 12:07

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_uploadedzipfile_progress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedzipfile',
            name='uploaded_zip_file',
            field=models.FileField(upload_to='files/', validators=[app.models.validate_zip_file_size]),
        ),
        migrations.AlterField(
            model_name='user',
            name='bot_icon',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/images/'),
        ),
    ]
